esphome:
  name: fridans-rollo-1
  friendly_name: Fridans Rollo 1

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "j8LBqKNckowRjCzPMGbrIJj1PMt2SlzDie9eE1fL8KQ="

stepper:
  - platform: uln2003
    id: stepper1
    pin_a: 1
    pin_b: 2
    pin_c: 3
    pin_d: 4
    max_speed: 100

    acceleration: inf
    deceleration: inf

button:
  - platform: template
    id: button_open
    name: open
    on_press: 
      then:
        - logger.log: "button 'open' pressed"
        - stepper.report_position: 
            id: stepper1
            position: 0
        - stepper.set_target: 
            id: stepper1
            target: 20000
  - platform: template
    id: button_close
    name: close 
    on_press: 
      then:
        - logger.log: "button 'close' pressed"
        - stepper.report_position: 
            id: stepper1
            position: 0
        - stepper.set_target: 
            id: stepper1
            target: -20000
            
ota:
  - platform: esphome
    password: "fbc404d82f30fdba34478223f774a52c"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fridans-Rollo-1 Fallback Hotspot"
    password: "H9oWMz71cboi"

captive_portal:
    
